import type { Metadata } from "next";
import { Outfit } from "next/font/google"; // Import Outfit font
import "./globals.css";
import Header from "./_components/Header";
import NextAuthSessionProvider from './provider'
import { Toaster } from "sonner";

// Configure the Outfit font
const outfitFont = Outfit({
  variable: "--font-outfit", // Define a custom CSS variable for the font
  subsets: ["latin"],        // Specify the subset
  weight: ["300", "400", "500", "600", "700"], // Specify weights if needed
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfitFont.variable} antialiased`}>
      <NextAuthSessionProvider>
        <div className="mx-6 md:mx-16">
          <Header />
          <Toaster />
          {children}
        </div>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
